# Generated by Django 5.2.10 on 2026-02-01 15:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabase_id', models.UUIDField(blank=True, db_index=True, help_text='UUID from Supabase Auth (auth.users.id)', null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Adresse email')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format: '+213XXXXXXXXX' ou '0XXXXXXXXX'", regex='^(\\+213|0)(5|6|7)[0-9]{8}$')], verbose_name='Téléphone')),
                ('wilaya', models.CharField(blank=True, choices=[('01', 'Adrar'), ('02', 'Chlef'), ('03', 'Laghouat'), ('04', 'Oum El Bouaghi'), ('05', 'Batna'), ('06', 'Béjaïa'), ('07', 'Biskra'), ('08', 'Béchar'), ('09', 'Blida'), ('10', 'Bouira'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Alger'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', "M'Sila"), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arréridj'), ('35', 'Boumerdès'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Aïn Defla'), ('45', 'Naâma'), ('46', 'Aïn Témouchent'), ('47', 'Ghardaïa'), ('48', 'Relizane'), ('49', "El M'Ghair"), ('50', 'El Meniaa'), ('51', 'Ouled Djellal'), ('52', 'Bordj Badji Mokhtar'), ('53', 'Béni Abbès'), ('54', 'Timimoun'), ('55', 'Touggourt'), ('56', 'Djanet'), ('57', 'In Salah'), ('58', 'In Guezzam')], max_length=2, verbose_name='Wilaya')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('avatar_url', models.URLField(blank=True, help_text='URL from OAuth provider (Google, Facebook)', max_length=500, null=True, verbose_name='URL avatar externe')),
                ('role', models.CharField(choices=[('USER', 'Utilisateur'), ('INSTRUCTOR', 'Formateur'), ('ADMIN', 'Administrateur'), ('SUPER_ADMIN', 'Super Administrateur')], db_index=True, default='USER', max_length=20, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('DELETED', 'Supprimé')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('is_staff', models.BooleanField(default=False, help_text="Autorise l'accès à l'interface d'administration Django.", verbose_name='Accès admin')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'utilisateur peut se connecter.", verbose_name='Compte actif')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', max_length=2, verbose_name='Langue préférée')),
                ('newsletter_subscribed', models.BooleanField(default=False, verbose_name='Abonné newsletter')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('reward_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de parrainage',
                'verbose_name_plural': 'Codes de parrainage',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='users.referralcode')),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['supabase_id'], name='users_user_supabas_e77bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='users_user_role_6e67fb_idx'),
        ),
    ]
