# Generated by Django 5.2.10 on 2026-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook')], default='EMAIL', max_length=20, verbose_name="Fournisseur d'authentification"),
        ),
    ]
