# Generated by Django 5.2.12 on 2026-04-15 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Pourquoi souhaitez-vous supprimer votre compte ?', verbose_name='Raison de suppression')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, help_text="Commentaire de l'administrateur", verbose_name='Notes admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin qui a traité la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de suppression',
                'verbose_name_plural': 'Demandes de suppression',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_accou_user_id_2109a7_idx'), models.Index(fields=['status', '-created_at'], name='users_accou_status_861d78_idx')],
            },
        ),
    ]
