# Generated by Django 5.2.12 on 2026-04-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_accountdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde des récompenses de parrainage en DZD', max_digits=10, verbose_name='Solde parrainage'),
        ),
    ]
