# Generated by Django 5.2.12 on 2026-04-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='users_notif_user_id_c37f16_idx',
            old_name='notif_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='users_notif_user_id_1be17e_idx',
            old_name='notif_user_read_idx',
        ),
    ]
