# Generated by Django 5.2.10 on 2026-03-07 10:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Machine-readable key, e.g. first_lesson, quiz_master', max_length=50, unique=True, verbose_name='Clé unique')),
                ('title', models.JSONField(default=dict, help_text='i18n: {"fr": "...", "en": "...", "ar": "..."}', verbose_name='Titre')),
                ('description', models.JSONField(default=dict, help_text='i18n: {"fr": "...", "en": "...", "ar": "..."}', verbose_name='Description')),
                ('icon', models.CharField(default='TrophyIcon', help_text='Heroicon name, e.g. AcademicCapIcon, FireIcon', max_length=50, verbose_name='Icône')),
                ('xp_reward', models.PositiveIntegerField(default=20, help_text='XP awarded when achievement is unlocked', verbose_name='Récompense XP')),
                ('condition_type', models.CharField(choices=[('lessons_completed', 'Leçons terminées'), ('quizzes_passed', 'Quiz réussis'), ('courses_completed', 'Formations terminées'), ('streak_days', 'Jours consécutifs'), ('total_xp', 'XP total atteint'), ('perfect_quiz', 'Quiz parfait')], max_length=30, verbose_name='Type de condition')),
                ('condition_value', models.PositiveIntegerField(default=1, help_text='Threshold value for the condition (e.g. 10 lessons)', verbose_name='Valeur seuil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Définition de succès',
                'verbose_name_plural': 'Définitions de succès',
                'ordering': ['condition_type', 'condition_value'],
            },
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='XP Total')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Niveau')),
                ('level_title', models.JSONField(blank=True, default=dict, help_text='i18n level title, e.g. {"fr": "Débutant", "en": "Beginner"}', verbose_name='Titre du niveau')),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Jours consécutifs')),
                ('streak_last_date', models.DateField(blank=True, help_text='Last date the user earned XP', null=True, verbose_name='Dernière activité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil XP',
                'verbose_name_plural': 'Profils XP',
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('alltime', 'Tout temps')], max_length=10, verbose_name='Période')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='XP Total')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Niveau')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Classement')),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cache classement',
                'verbose_name_plural': 'Cache classements',
                'ordering': ['period', 'rank'],
                'indexes': [models.Index(fields=['period', 'rank'], name='gameficatio_period_7ee9e7_idx')],
                'unique_together': {('user', 'period')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='gamefication.achievementdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Succès utilisateur',
                'verbose_name_plural': 'Succès utilisateurs',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('lesson', 'Leçon terminée'), ('quiz', 'Quiz réussi'), ('final_quiz', 'Examen final réussi'), ('achievement', 'Succès débloqué'), ('bonus', 'Bonus'), ('enrollment', 'Inscription')], max_length=20, verbose_name='Source')),
                ('amount', models.IntegerField(help_text='Positive = gain, negative = penalty', verbose_name='Montant XP')),
                ('reference_id', models.CharField(blank=True, help_text='UUID or identifier of the source object (lesson, quiz, etc.)', max_length=255, verbose_name='Référence')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction XP',
                'verbose_name_plural': 'Transactions XP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'source'], name='gameficatio_user_id_483bdc_idx'), models.Index(fields=['user', '-created_at'], name='gameficatio_user_id_cc82ff_idx')],
            },
        ),
    ]
