# Generated by Django 5.2.10 on 2026-03-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userxp',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Record de jours'),
        ),
    ]
