# Generated by Django 5.2.10 on 2026-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefication', '0002_userxp_longest_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='userxp',
            name='visible_on_leaderboard',
            field=models.BooleanField(default=True, help_text='Whether this user appears on the public leaderboard', verbose_name='Visible sur le classement'),
        ),
    ]
