# Generated by Django 5.2.10 on 2026-02-12 16:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Nom (FR)')),
                ('nameAr', models.CharField(blank=True, max_length=120, verbose_name='Nom (AR)')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Heroicon name or emoji', max_length=60, verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('slide', 'Diaporama'), ('video', 'Vidéo'), ('text', 'Texte'), ('audio', 'Audio')], default='slide', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Durée (secondes)')),
                ('audioUrl', models.URLField(blank=True, max_length=600, verbose_name='URL audio')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Slide visual_content + narration_script matching TS Slide', verbose_name='Contenu (JSON)')),
                ('slide_type', models.CharField(blank=True, help_text='e.g. bullet_points, pillars, …', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('intro_text', models.TextField(blank=True)),
                ('pass_threshold', models.PositiveIntegerField(default=70, help_text='Percentage required to pass (0-100)')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='0 = unlimited')),
                ('xp_reward', models.PositiveIntegerField(default=10, help_text='XP points awarded on pass')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Total course duration in hours', verbose_name='Durée (heures)')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('students', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True, help_text='Thumbnail stored in Supabase Storage', max_length=600, verbose_name='Image URL')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Prix (DZD)')),
                ('originalPrice', models.PositiveIntegerField(default=0, verbose_name='Prix original')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='JSON array of prerequisite strings', verbose_name='Prérequis')),
                ('whatYouLearn', models.JSONField(blank=True, default=list, help_text='JSON array of learning objectives', verbose_name='Ce que vous apprendrez')),
                ('language', models.CharField(default='English', max_length=60)),
                ('certificate', models.BooleanField(default=True, verbose_name='Certificat inclus')),
                ('lastUpdated', models.DateField(blank=True, null=True, verbose_name='Dernière MàJ')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=20)),
                ('audioBasePath', models.CharField(blank=True, help_text='Base URL for audio files in Supabase Storage', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='formation.category')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Final score achieved', max_digits=5)),
                ('code', models.CharField(db_index=True, help_text='Unique verification code', max_length=40, unique=True)),
                ('issuedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='formation.course')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-issuedAt'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.DecimalField(decimal_places=2, default=0, help_text='Overall completion percentage 0-100', max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='formation.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('slide_index', models.PositiveIntegerField(default=0, help_text='Slide index the note is attached to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='formation.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='formation.lesson')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['slide_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_slide', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_position', models.PositiveIntegerField(default=0, help_text='Audio position in seconds')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='formation.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='formation.lesson')),
            ],
            options={
                'verbose_name': 'Progression leçon',
                'verbose_name_plural': 'Progressions leçons',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total (DZD)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('paymentMethod', models.CharField(choices=[('ccp', 'CCP'), ('baridimob', 'BaridiMob'), ('card', 'Carte bancaire'), ('edahabia', 'Edahabia'), ('free', 'Gratuit')], default='ccp', max_length=30)),
                ('paymentRef', models.CharField(blank=True, max_length=200, verbose_name='Référence de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Prix unitaire (DZD)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='formation.course')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='formation.order')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Score percentage 0-100', max_digits=5)),
                ('answers', models.JSONField(default=dict, help_text='Map of question_id -> selected_option_index')),
                ('passed', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('feedback', models.JSONField(blank=True, default=list, help_text='Per-question feedback returned to frontend')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='formation.enrollment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='formation.quiz')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('multiple_choice', 'QCM'), ('true_false', 'Vrai/Faux'), ('scenario', 'Scénario')], default='multiple_choice', max_length=30)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list, help_text='JSON array of option strings')),
                ('correct_answer', models.PositiveIntegerField(help_text='0-based index of the correct option')),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=20)),
                ('category', models.CharField(blank=True, help_text='e.g. general, memorisation, raisonnement', max_length=60)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formation.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('teaser', 'Teaser'), ('introduction', 'Introduction'), ('module', 'Module'), ('conclusion', 'Conclusion')], default='module', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Ordering weight inside the course')),
                ('audioFileIndex', models.PositiveIntegerField(default=0, help_text='Starting index in the audio files array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='formation.course')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='formation.section'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='formation.section'),
        ),
        migrations.CreateModel(
            name='ShareToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('token', 'Par lien')], default='token', max_length=20)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='formation.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien de partage',
                'verbose_name_plural': 'Liens de partage',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'level'], name='formation_c_status_076b97_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'status'], name='formation_c_categor_e1f0b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'status'], name='formation_e_user_id_833fc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('section', 'sequence')},
        ),
    ]
