# Generated by Django 5.2.10 on 2026-02-12 17:29

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='nameAr',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.JSONField(default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}', validators=[content.models.validate_translation_json], verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.JSONField(default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}', validators=[content.models.validate_translation_json], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": ["..."], "en": ["..."], "ar": ["..."]} — array per language', verbose_name='Prérequis'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.JSONField(default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}', validators=[content.models.validate_translation_json], verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='whatYouLearn',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": ["..."], "en": ["..."], "ar": ["..."]} — array per language', verbose_name='Ce que vous apprendrez'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audioUrl',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": "url", "en": "url", "ar": "url"} — per-language audio', verbose_name='URL audio'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": {slides...}, "en": {slides...}, "ar": {slides...}}', verbose_name='Contenu (JSON)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.JSONField(default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}', validators=[content.models.validate_translation_json], verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='intro_text',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}', verbose_name="Texte d'introduction"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.JSONField(default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}', validators=[content.models.validate_translation_json], verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.PositiveIntegerField(help_text='0-based index of the correct option (language-independent)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}', verbose_name='Explication'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='options',
            field=models.JSONField(default=dict, help_text='{"fr": ["A", "B", "C"], "en": ["A", "B", "C"], "ar": ["أ", "ب", "ج"]}', verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.JSONField(default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}', validators=[content.models.validate_translation_json], verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.JSONField(default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}', validators=[content.models.validate_translation_json], verbose_name='Titre'),
        ),
    ]
