# Generated by Django 5.2.10 on 2026-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_alter_category_options_remove_category_namear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Course thumbnail image', null=True, upload_to='courses/thumbnails/', verbose_name='Image'),
        ),
    ]
