# Generated by Django 5.2.10 on 2026-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audioUrl',
            field=models.URLField(blank=True, help_text='Audio file URL for this lesson', max_length=600, verbose_name='URL audio'),
        ),
    ]
