# Generated by Django 5.2.10 on 2026-02-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_alter_lesson_audiourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titre'),
        ),
    ]
