# Generated by Django 5.2.10 on 2026-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, default='', help_text='Thumbnail URL in Supabase Storage (courses/ bucket)', max_length=600, verbose_name='Image URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list, help_text='["item1", "item2", ...] — simple array of strings', verbose_name='Prérequis'),
        ),
        migrations.AlterField(
            model_name='course',
            name='whatYouLearn',
            field=models.JSONField(blank=True, default=list, help_text='["item1", "item2", ...] — simple array of strings', verbose_name='Ce que vous apprendrez'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.JSONField(blank=True, default=list, help_text='Slides data as a JSON array', verbose_name='Contenu (JSON)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='intro_text',
            field=models.TextField(blank=True, verbose_name="Texte d'introduction"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.PositiveIntegerField(help_text='0-based index of the correct option'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Explication'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='options',
            field=models.JSONField(default=list, help_text='["Option A", "Option B", "Option C"]', verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titre'),
        ),
    ]
