# Generated by Django 5.2.10 on 2026-02-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_alter_course_description_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audioUrl',
            field=models.FileField(blank=True, help_text='Audio file for this lesson', upload_to='lessons/audio/', verbose_name='Fichier audio'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Lesson content as a JSON object', verbose_name='Contenu (JSON)'),
        ),
    ]
