# Generated by Django 5.2.10 on 2026-02-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0007_alter_lesson_audiourl_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audioUrl',
            field=models.URLField(blank=True, help_text='Public URL of audio file in Supabase (audios/<course_id>/...)', max_length=600, verbose_name='URL audio'),
        ),
    ]
