# Generated by Django 5.2.10 on 2026-02-14 09:03

import formation.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_alter_lesson_audiourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audioUrl',
            field=models.FileField(blank=True, help_text='Audio file — uploaded to Supabase audios/<course_id>/', storage=formation.storage.SupabaseAudioStorage(), upload_to=formation.storage.audio_upload_path, verbose_name='Fichier audio'),
        ),
    ]
