# Generated by Django 5.2.10 on 2026-02-17 09:57

import django.db.models.deletion
import formation.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0009_alter_lesson_audiourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='URL to the generated PDF certificate in Supabase', max_length=500, verbose_name='PDF URL'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final quiz score achieved', max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Course thumbnail — uploaded to Supabase images/ bucket', storage=formation.storage.SupabaseImageStorage(), upload_to=formation.storage.course_image_upload_path, verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='FinalQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Examen Final', max_length=300, verbose_name='Titre')),
                ('num_questions', models.PositiveIntegerField(default=20, help_text='Number of random questions to pull from section quizzes')),
                ('pass_threshold', models.PositiveIntegerField(default=70, help_text='Percentage required to pass (0-100)')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='0 = unlimited')),
                ('xp_reward', models.PositiveIntegerField(default=50, help_text='XP points awarded on pass')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_quiz', to='formation.course')),
            ],
            options={
                'verbose_name': 'Examen Final',
                'verbose_name_plural': 'Examens Finaux',
            },
        ),
        migrations.CreateModel(
            name='FinalQuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Score percentage 0-100', max_digits=5)),
                ('answers', models.JSONField(default=dict, help_text='Map of question_id -> selected_option_index')),
                ('questions_snapshot', models.JSONField(default=list, help_text='Snapshot of random question IDs selected for this attempt')),
                ('passed', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('feedback', models.JSONField(blank=True, default=list, help_text='Per-question feedback returned to frontend')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_quiz_attempts', to='formation.enrollment')),
                ('final_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='formation.finalquiz')),
            ],
            options={
                'verbose_name': 'Tentative examen final',
                'verbose_name_plural': 'Tentatives examen final',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
