# Generated by Django 5.2.10 on 2026-02-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0011_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to='formation.course'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1-5 star rating'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='review_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
