# Generated by Django 5.2.10 on 2026-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0012_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100). Price is auto-calculated from originalPrice.', verbose_name='Réduction (%)'),
        ),
    ]
