# Generated by Django 5.2.10 on 2026-02-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0013_add_discount_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('initialisation', 'Initialisation'), ('approfondissement', 'Approfondissement'), ('advanced', 'Avancé')], default='initialisation', max_length=20),
        ),
    ]
