# Generated by Django 5.2.10 on 2026-02-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0014_change_course_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile'), ('expert', 'Expert')], default='easy', max_length=20),
        ),
    ]
