# Generated by Django 5.2.10 on 2026-03-11 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0015_alter_quizquestion_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='display_mode',
            field=models.CharField(choices=[('narration', 'Narration uniquement'), ('slide', 'Slide uniquement'), ('both', 'Les deux')], default='both', help_text='narration, slide, or both', max_length=20, verbose_name="Mode d'affichage"),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Nom')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('slides', 'Slides'), ('video', 'Vidéo'), ('other', 'Autre')], default='pdf', max_length=20)),
                ('size', models.CharField(blank=True, help_text='Human-readable size, e.g. "2.5 MB"', max_length=60, verbose_name='Taille')),
                ('file', models.FileField(blank=True, help_text='Uploaded material file', upload_to='materials/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, help_text='External URL if file is not uploaded', verbose_name='URL externe')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='formation.course')),
            ],
            options={
                'verbose_name': 'Support de cours',
                'verbose_name_plural': 'Supports de cours',
                'ordering': ['sequence'],
            },
        ),
    ]
