# Generated by Django 5.2.10 on 2026-03-11 11:45

import formation.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0016_lesson_display_mode_coursematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded to Supabase materials/<course_id>/', storage=formation.storage.SupabaseMaterialStorage(), upload_to=formation.storage.material_upload_path, verbose_name='Fichier'),
        ),
    ]
