# Generated by Django 5.2.10 on 2026-03-12 14:59

import formation.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0017_alter_coursematerial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='diapositiveUrl',
            field=models.FileField(blank=True, help_text='Diapositive file — uploaded to Supabase Diapositive/<course_id>/', storage=formation.storage.SupabaseDiapositiveStorage(), upload_to=formation.storage.diapositive_upload_path, verbose_name='Fichier diapositive'),
        ),
    ]
