# Generated by Django 5.2.10 on 2026-03-13 16:56

import formation.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0018_lesson_diapositiveurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalquiz',
            name='motivation_audio',
            field=models.FileField(blank=True, help_text='Audio file played when student fails — uploaded to Supabase', storage=formation.storage.SupabaseAudioStorage(), upload_to=formation.storage.audio_upload_path, verbose_name='Audio de motivation'),
        ),
    ]
