# Generated by Django 5.2.10 on 2026-03-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0019_add_motivation_audio_to_finalquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('initialisation', 'Initialisation'), ('approfondissement', 'Approfondissement'), ('etude_de_cas', 'Étude de cas')], default='initialisation', max_length=20),
        ),
    ]
