# Generated by Django 5.2.10 on 2026-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0020_change_advanced_to_etude_de_cas'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chargily_checkout_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Chargily Checkout ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Chargily Checkout URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('ccp', 'CCP'), ('baridimob', 'BaridiMob'), ('card', 'Carte bancaire'), ('edahabia', 'Edahabia'), ('cib', 'CIB'), ('free', 'Gratuit')], default='ccp', max_length=30),
        ),
    ]
