# Generated by Django 5.2.10 on 2026-03-27 09:13

import django.db.models.deletion
import formation.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0021_order_chargily_checkout_id_order_checkout_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalQuizAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_percentage', models.PositiveIntegerField(default=0, help_text='Inclusive lower bound of score range (0-100)')),
                ('max_percentage', models.PositiveIntegerField(default=100, help_text='Inclusive upper bound of score range (0-100)')),
                ('label', models.CharField(blank=True, help_text='Optional label, e.g. "Keep trying!" or "Almost there!"', max_length=200)),
                ('audio', models.FileField(blank=True, help_text='Audio file for this score range — uploaded to Supabase', storage=formation.storage.SupabaseAudioStorage(), upload_to=formation.storage.audio_upload_path, verbose_name='Audio file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_entries', to='formation.finalquiz')),
            ],
            options={
                'verbose_name': 'Audio par pourcentage',
                'verbose_name_plural': 'Audios par pourcentage',
                'ordering': ['min_percentage'],
            },
        ),
    ]
