# Generated by Django 5.2.10 on 2026-03-27 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0022_add_finalquizaudio_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(help_text='Email du destinataire', max_length=254)),
                ('gift_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('message', models.TextField(blank=True, help_text='Message personnel du donneur')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('claimed', 'Réclamé'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration du cadeau', null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='formation.course')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='formation.order')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='Lié au compte quand le cadeau est réclamé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cadeau de cours',
                'verbose_name_plural': 'Cadeaux de cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Code unique (ex: WELCOME20, SUMMER50)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe (DZD)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Valeur du réduction (% ou DZD)', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Combien de fois un même utilisateur peut utiliser ce code')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('min_order_total', models.PositiveIntegerField(default=0, help_text='Montant minimum de commande (DZD) — 0 = pas de minimum')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Vide = applicable à tous les cours', related_name='promo_codes', to='formation.course')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_applied', models.PositiveIntegerField(default=0, help_text='Discount amount in DZD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_usages', to='formation.order')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='formation.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisation code promo',
                'verbose_name_plural': 'Utilisations codes promo',
            },
        ),
    ]
