# Generated by Django 5.2.12 on 2026-04-07 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0023_add_promo_gift_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='audioFileIndex',
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('teaser', 'Teaser'), ('introduction', 'Introduction'), ('initialisation', 'Initialisation'), ('approfondissement', 'Approfondissement'), ('etude_de_cas', 'Étude de cas'), ('conclusion', 'Conclusion'), ('module', 'Module')], default='module', max_length=20),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Ordering weight inside the section')),
                ('audioFileIndex', models.PositiveIntegerField(default=0, help_text='Starting index in the audio files array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='formation.section')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['sequence'],
                'unique_together': {('section', 'sequence')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='formation.module'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'sequence')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section',
        ),
    ]
