# Generated by Django 5.2.12 on 2026-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0024_remove_section_audiofileindex_alter_section_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('TEASER', 'Teaser'), ('INTRO', 'Introduction'), ('INIT', 'Initialisation'), ('APPRO', 'Approfondissement'), ('CAS', 'Étude de cas'), ('CONCL', 'Conclusion')], default='APPRO', max_length=20),
        ),
    ]
