# Generated by Django 5.2.12 on 2026-05-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0026_section_type_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Cochez pour rendre ce cours gratuit (prix = 0 DZD).', verbose_name='Cours gratuit'),
        ),
    ]
