# Generated by Django 5.2.12 on 2026-08-04 09:15

import content.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0028_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('title', models.JSONField(default=dict, help_text='{"fr": "Flash Sale!", "en": "Flash Sale!", "ar": "عرض محدود!"}', validators=[content.models.validate_translation_json], verbose_name='Titre (Traduit)')),
                ('subtitle', models.JSONField(blank=True, default=dict, validators=[content.models.validate_translation_json], verbose_name='Sous-titre (Traduit)')),
                ('discount_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de réduction (%)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de fin')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='Afficher le compte à rebours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campagne Marketing',
                'verbose_name_plural': 'Campagnes Marketing',
            },
            bases=(models.Model, content.models.TranslatableFieldMixin),
        ),
    ]
