"""
Django settings for ooskillsbackend project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',  # All Render subdomains
    'ooskills-backend.onrender.com',
    '[::1]', 
    'host.docker.internal',
    'api.ooskills.com',
    '178.104.214.238'
      # Your specific Render domain
]

# Add custom domain from environment variable if set
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',

    'django_filters',

    # Local apps
    'users',
    'content',
    'formation',
    'gamefication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware - must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ooskillsbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ooskillsbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '6543'),
        'OPTIONS': {
            'sslmode': 'require',
            'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '10')),
            'keepalives': 1,
            'keepalives_idle': int(os.environ.get('DB_KEEPALIVES_IDLE', '30')),
            'keepalives_interval': int(os.environ.get('DB_KEEPALIVES_INTERVAL', '10')),
            'keepalives_count': int(os.environ.get('DB_KEEPALIVES_COUNT', '5')),
        },
        # On managed poolers (e.g. pgbouncer/supabase), stale persistent
        # connections frequently cause "server closed connection" / SSL EOF errors.
        # Default to short-lived connections, overridable via env.
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '0')),
        'CONN_HEALTH_CHECKS': True,
    }
}


# =============================================================================
# CUSTOM USER MODEL
# =============================================================================

AUTH_USER_MODEL = 'users.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Large file upload settings (ZIP imports can be hundreds of MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024   # 500 MB — max request body
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024     # 10 MB — files larger than this are streamed to disk
FILE_UPLOAD_TEMP_DIR = str(BASE_DIR / 'tmp_uploads')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# REST FRAMEWORK CONFIGURATION
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.ResilientJWTAuthentication',  # Local JWT with DB retry
        'users.authentication.SupabaseJWTAuthentication',  # Supabase Auth (fallback)
        'rest_framework.authentication.SessionAuthentication',  # For browsable API
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # ---------------------------------------------------------------------------
    # Rate limiting — global defaults + scoped overrides on sensitive endpoints.
    # Buckets are enforced per IP (anon) or per user (authenticated).
    # ---------------------------------------------------------------------------
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Global defaults
        'anon': '100/hour',
        'user': '1000/hour',
        # Auth — tightly limited to prevent brute-force / abuse
        'auth_login': '10/min',
        'auth_register': '5/min',
        'auth_social': '10/min',
        'auth_refresh': '30/min',
        'auth_email': '5/min',        # resend verification
        'auth_password_reset': '3/min',
        # API actions with real-world cost
        'enrollment': '20/hour',
        'quiz_attempt': '10/hour',
        'order_create': '10/hour',
        'gift_create': '5/hour',
    },
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        ['rest_framework.renderers.JSONRenderer', 'rest_framework.renderers.BrowsableAPIRenderer']
        if DEBUG else
        ['rest_framework.renderers.JSONRenderer']
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# =============================================================================
# DRF-SPECTACULAR (SWAGGER/OPENAPI) CONFIGURATION
# =============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'OOSkills API',
    'DESCRIPTION': 'API documentation for OOSkills Platform - E-learning platform for Algeria',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
    },
    'SECURITY': [
        {'BearerAuth': []},
    ],
}


# =============================================================================
# AUTHENTICATION BACKENDS
# =============================================================================

AUTHENTICATION_BACKENDS = [
    'users.authentication.SupabaseAuthBackend',  # Supabase Auth
    'django.contrib.auth.backends.ModelBackend',  # Django default
]


# =============================================================================
# JWT CONFIGURATION (Local Django JWT)
# =============================================================================

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,  # Stateless JWT - no database storage
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',  # UUID field
    'USER_ID_CLAIM': 'user_id',
}


# =============================================================================
# SUPABASE CONFIGURATION
# =============================================================================

SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_ANON_KEY = os.environ.get('SUPABASE_ANON_KEY', '')
SUPABASE_SERVICE_ROLE_KEY = os.environ.get('SUPABASE_SERVICE_ROLE_KEY', '')
SUPABASE_JWT_SECRET = os.environ.get('SUPABASE_JWT_SECRET', '')


# =============================================================================
# GOOGLE OAUTH CONFIGURATION
# =============================================================================

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')


# =============================================================================
# FACEBOOK OAUTH CONFIGURATION
# =============================================================================

FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID', '')
FACEBOOK_APP_SECRET = os.environ.get('FACEBOOK_APP_SECRET', '')


# =============================================================================
# CORS CONFIGURATION
# =============================================================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://ooskills.com",            # ← Your frontend domain
    "https://www.ooskills.com",
]

CORS_ALLOW_CREDENTIALS = True

# For development only - remove in production
CORS_ALLOW_ALL_ORIGINS = DEBUG


# =============================================================================
# CACHING CONFIGURATION
# =============================================================================

REDIS_URL = os.environ.get('REDIS_URL', '')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'RETRY_ON_TIMEOUT': True,
                'IGNORE_EXCEPTIONS': True,  # Graceful degradation
            },
            'KEY_PREFIX': 'ooskills',
            'TIMEOUT': 300,  # Default TTL: 5 minutes
        }
    }
else:
    # Fallback: in-memory cache for local dev when Redis is not configured
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'ooskills-cache',
            'TIMEOUT': 300,
        }
    }


# =============================================================================
# LANGUAGE/INTERNATIONALIZATION
# =============================================================================

LANGUAGES = [
    ('fr', 'French'),
    ('ar', 'Arabic'),
    ('en', 'English'),
]

# CMS supported languages (used by content app)
CMS_LANGUAGES = ['fr', 'ar', 'en']
CMS_DEFAULT_LANGUAGE = 'fr'


# =============================================================================
# EMAIL CONFIGURATION (Resend)
# =============================================================================

RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'resend@ooskills.com')


# =============================================================================
# FRONTEND CONFIGURATION
# =============================================================================

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# Token expiration time in hours
EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS = 24


# =============================================================================
# CHARGILY PAY CONFIGURATION
# =============================================================================

CHARGILY_KEY = os.environ.get('CHARGILY_KEY', '')
CHARGILY_SECRET = os.environ.get('CHARGILY_SECRET', '')
CHARGILY_URL = os.environ.get('CHARGILY_URL', 'https://pay.chargily.net/test/api/v2/')

# Ngrok URL for local webhook testing (e.g. https://abc123.ngrok-free.app)
NGROK_URL = os.environ.get('NGROK_URL', '')

if NGROK_URL:
    from urllib.parse import urlparse
    _ngrok_host = urlparse(NGROK_URL).hostname
    if _ngrok_host and _ngrok_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_ngrok_host)
    CSRF_TRUSTED_ORIGINS = [NGROK_URL]


# =============================================================================
# CLOUDFLARE R2 STORAGE CONFIGURATION
# =============================================================================
# R2 is S3-compatible. Get credentials from Cloudflare dashboard:
#   Workers & Pages → R2 → Manage R2 API tokens
#
# Buckets used (create these in the R2 dashboard):
#   audios, images, materials, Diapositive, avatars
#
# For each public bucket, set a custom domain or enable the r2.dev subdomain
# and set the corresponding R2_PUBLIC_URL_* env var.

R2_ACCOUNT_ID = os.environ.get('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY', '')

# S3-compatible endpoint (boto3 endpoint_url)
R2_ENDPOINT_URL = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com" if R2_ACCOUNT_ID else ''

# Public base URLs per bucket — set to your r2.dev subdomain or custom domain.
# Example:  https://pub-abc123.r2.dev  or  https://cdn.ooskills.com
R2_PUBLIC_URLS = {
    'audios':      os.environ.get('R2_PUBLIC_URL_AUDIOS', ''),
    'images':      os.environ.get('R2_PUBLIC_URL_IMAGES', ''),
    'materials':   os.environ.get('R2_PUBLIC_URL_MATERIALS', ''),
    'diapositive': os.environ.get('R2_PUBLIC_URL_DIAPOSITIVE', ''),
    'avatars':     os.environ.get('R2_PUBLIC_URL_AVATARS', ''),
}
