# Generated by Django 5.2.10 on 2026-02-01 15:11

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('question', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('answer', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Supports long text/HTML', validators=[content.models.validate_translation_json])),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order'],
            },
            bases=(models.Model, content.models.TranslatableFieldMixin),
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('subtitle', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Features Section',
                'verbose_name_plural': 'Features Sections',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, content.models.TranslatableFieldMixin),
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('subtitle', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('description', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('background_image_url', models.URLField(blank=True, help_text='External URL for background image (used if no file uploaded)', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, content.models.TranslatableFieldMixin),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('logo_url', models.URLField(blank=True, help_text='External URL for logo (used if no file uploaded)', max_length=500, null=True)),
                ('website_url', models.URLField(blank=True, help_text="Partner's website URL", max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('author_name', models.CharField(max_length=200)),
                ('author_title', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Author role/position')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('author_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('content', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating out of 5')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
            bases=(models.Model, content.models.TranslatableFieldMixin),
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name (e.g., 'rocket', 'shield', 'zap')", max_length=100)),
                ('icon_image', models.ImageField(blank=True, help_text='Custom icon image (takes precedence over icon name)', null=True, upload_to='features/icons/')),
                ('icon_url', models.URLField(blank=True, help_text='External URL for icon image', max_length=500, null=True)),
                ('title', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('description', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.featuressection')),
            ],
            options={
                'verbose_name': 'Feature Item',
                'verbose_name_plural': 'Feature Items',
                'ordering': ['order'],
            },
            bases=(models.Model, content.models.TranslatableFieldMixin),
        ),
    ]
