# Generated by Django 5.0.6 on 2026-02-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='badge_text',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Badge/label text above title'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='card_subtitle',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Card subtitle text'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='card_title',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Card title text'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='primary_cta_text',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Primary call-to-action button text'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_highlight',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Brand name or highlighted part of title'),
        ),
    ]
