# Generated by Django 5.0.6 on 2026-02-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_hero_cta_and_card_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='secondary_cta_text',
            field=models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Secondary call-to-action button text'),
        ),
    ]
