# Generated by Django 5.0.6 on 2026-02-02 17:14

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_secondary_cta_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Site name')),
                ('site_tagline', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Site tagline/slogan')),
                ('default_language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', help_text='Default language for the site', max_length=5)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=50)),
                ('meta_title', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - SEO meta title')),
                ('meta_description', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - SEO meta description')),
                ('meta_keywords', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - SEO meta keywords')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social media sharing', null=True, upload_to='seo/')),
                ('og_image_url', models.URLField(blank=True, help_text='External URL for OG image', max_length=500, null=True)),
                ('dark_mode_enabled', models.BooleanField(default=True, help_text='Allow users to switch between light and dark themes')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Enable notification badges in admin panel')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (shows maintenance page to visitors)')),
                ('registration_enabled', models.BooleanField(default=True, help_text='Allow new user registrations')),
                ('facebook_url', models.URLField(blank=True, max_length=500)),
                ('twitter_url', models.URLField(blank=True, max_length=500)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('youtube_url', models.URLField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_address', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."} - Physical address')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
            bases=(models.Model, content.models.TranslatableFieldMixin),
        ),
    ]
