# Generated by Django 5.0.6 on 2026-02-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO meta keywords (comma-separated)', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, help_text='Site name', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(blank=True, help_text='Site tagline/slogan', max_length=500),
        ),
    ]
