# Generated by Django 5.0.6 on 2026-02-04 11:10

import content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_simplify_site_settings_to_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('subtitle', models.JSONField(default=dict, help_text='{"fr": "...", "ar": "...", "en": "..."}', validators=[content.models.validate_translation_json])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Sections',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, content.models.TranslatableFieldMixin),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.faqsection'),
        ),
    ]
