# Generated by Django 5.2.12 on 2026-08-04 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_add_faq_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='welcome_discount_percentage',
            field=models.PositiveIntegerField(default=20, help_text="Extra discount % applied on top for a user's first purchase (no prior paid orders)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
