# Generated by Django 5.2.12 on 2026-08-17 21:38

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}')),
                ('subtitle', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."}')),
                ('cta_text', models.JSONField(blank=True, default=dict, help_text='{"fr": "...", "en": "...", "ar": "..."} - Button text')),
                ('launch_date', models.DateTimeField(help_text='Target date/time the countdown counts down to')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section on the public landing page')),
            ],
            options={
                'verbose_name': 'Countdown Section',
                'verbose_name_plural': 'Countdown Section',
            },
            bases=(models.Model, content.models.TranslatableFieldMixin),
        ),
    ]
